export const LEARNALL_REQUESTED = 'LEARNALL_REQUESTED';
export const LEARNALL_SUCCESS = 'LEARNALL_SUCCESS';
export const LEARNALL_FAIL = 'LEARNALL_FAIL';
export const LEARNALLDETAILS_REQUESTED = 'LEARNALLDETAILS_REQUESTED';
export const LEARNALLDETAILS_SUCCESS = 'LEARNALLDETAILS_SUCCESS';
export const LEARNALLDETAILS_FAIL = 'LEARNALLDETAILS_FAIL';
export const LEARNFAVOURITE_REQUESTED = 'LEARNFAVOURITE_REQUESTED';
export const LEARNFAVOURITE_SUCCESS = 'LEARNFAVOURITE_SUCCESS';
export const LEARNFAVOURITE_FAIL = 'LEARNFAVOURITE_FAIL';
export const LEARNFAVOURITELIST_REQUESTED = 'LEARNFAVOURITELIST_REQUESTED';
export const LEARNFAVOURITELIST_SUCCESS = 'LEARNFAVOURITELIST_SUCCESS';
export const LEARNFAVOURITELIST_FAIL = 'LEARNFAVOURITELIST_FAIL';
export const LEARN_GUEST_FAVOURITE_REQUESTED = 'LEARN_GUEST_FAVOURITE_REQUESTED';
export const LEARN_GUEST_FAVOURITE_SUCCESS = 'LEARN_GUEST_FAVOURITE_SUCCESS';
export const LEARN_GUEST_FAVOURITE_FAIL = 'LEARN_GUEST_FAVOURITE_FAIL';
export const LEARN_REMOVE_FAVOURITE_REQUESTED = 'LEARN_REMOVE_FAVOURITE_REQUESTED';
export const LEARN_REMOVE_FAVOURITE_SUCCESS = 'LEARN_REMOVE_FAVOURITE_SUCCESS';
export const LEARN_REMOVE_FAVOURITE_FAIL = 'LEARN_REMOVE_FAVOURITE_FAIL';
export const LEARN_REMOVE_GUEST_FAVOURITE_REQUESTED = 'LEARN_REMOVE_GUEST_FAVOURITE_REQUESTED';
export const LEARN_REMOVE_GUEST_FAVOURITE_SUCCESS = 'LEARN_REMOVE_GUEST_FAVOURITE_SUCCESS';
export const LEARN_REMOVE_GUEST_FAVOURITE_FAIL = 'LEARN_REMOVE_GUEST_FAVOURITE_FAIL';
export const LEARN_REMOVE_ALL_FAVOURITES = 'LEARN_REMOVE_ALL_FAVOURITES';



