export const PLAY_REQUESTED = 'PLAY_REQUESTED';
export const PLAY_SUCCESS = 'PLAY_SUCCESS';
export const PLAY_FAIL = 'PLAY_FAIL';
export const PLAYDETAILS_REQUESTED = 'PLAYDETAILS_REQUESTED';
export const PLAYDETAILS_SUCCESS = 'PLAYDETAILS_SUCCESS';
export const PLAYDETAILS_FAIL = 'PLAYDETAILS_FAIL';
export const PLAYFAVOURITE_REQUESTED = 'PLAYFAVOURITE_REQUESTED';
export const PLAYFAVOURITE_SUCCESS = 'PLAYFAVOURITE_SUCCESS';
export const PLAYFAVOURITE_FAIL = 'PLAYFAVOURITE_FAIL';
export const PLAYFAVOURITELIST_REQUESTED = 'PLAYFAVOURITELIST_REQUESTED';
export const PLAYFAVOURITELIST_SUCCESS = 'PLAYFAVOURITELIST_SUCCESS';
export const PLAYFAVOURITELIST_FAIL = 'PLAYFAVOURITELIST_FAIL';
export const PLAY_GUEST_FAVOURITE_REQUESTED = 'PLAY_GUEST_FAVOURITE_REQUESTED';
export const PLAY_GUEST_FAVOURITE_SUCCESS = 'PLAY_GUEST_FAVOURITE_SUCCESS';
export const PLAY_GUEST_FAVOURITE_FAIL = 'PLAY_GUEST_FAVOURITE_FAIL';
export const PLAY_REMOVE_FAVOURITE_REQUESTED = 'PLAY_REMOVE_FAVOURITE_REQUESTED';
export const PLAY_REMOVE_FAVOURITE_SUCCESS = 'PLAY_REMOVE_FAVOURITE_SUCCESS';
export const PLAY_REMOVE_FAVOURITE_FAIL = 'PLAY_REMOVE_FAVOURITE_FAIL';
export const PLAY_REMOVE_GUEST_FAVOURITE_REQUESTED = 'PLAY_REMOVE_GUEST_FAVOURITE_REQUESTED';
export const PLAY_REMOVE_GUEST_FAVOURITE_SUCCESS = 'PLAY_REMOVE_GUEST_FAVOURITE_SUCCESS';
export const PLAY_REMOVE_GUEST_FAVOURITE_FAIL = 'PLAY_REMOVE_GUEST_FAVOURITE_FAIL';
export const PLAY_REMOVE_ALL_FAVOURITES = 'PLAY_REMOVE_ALL_FAVOURITES';



