export const CARDALL_REQUESTED = 'CARDALL_REQUESTED';
export const CARDALL_SUCCESS = 'CARDALL_SUCCESS';
export const CARDALL_FAIL = 'CARDALL_FAIL';
export const CARDALLDETAILS_REQUESTED = 'CARDALLDETAILS_REQUESTED';
export const CARDALLDETAILS_SUCCESS = 'CARDALLDETAILS_SUCCESS';
export const CARDALLDETAILS_FAIL = 'CARDALLDETAILS_FAIL';
export const CARDFAVOURITE_REQUESTED = 'CARDFAVOURITE_REQUESTED';
export const CARDFAVOURITE_SUCCESS = 'CARDFAVOURITE_SUCCESS';
export const CARDFAVOURITE_FAIL = 'CARDFAVOURITE_FAIL';
export const CARDFAVOURITELIST_REQUESTED = 'CARDFAVOURITELIST_REQUESTED';
export const CARDFAVOURITELIST_SUCCESS = 'CARDFAVOURITELIST_SUCCESS';
export const CARDFAVOURITELIST_FAIL = 'CARDFAVOURITELIST_FAIL';
export const CARD_GUEST_FAVOURITE_REQUESTED = 'CARD_GUEST_FAVOURITE_REQUESTED';
export const CARD_GUEST_FAVOURITE_SUCCESS = 'CARD_GUEST_FAVOURITE_SUCCESS';
export const CARD_GUEST_FAVOURITE_FAIL = 'CARD_GUEST_FAVOURITE_FAIL';
export const CARD_REMOVE_FAVOURITE_REQUESTED = 'CARD_REMOVE_FAVOURITE_REQUESTED';
export const CARD_REMOVE_FAVOURITE_SUCCESS = 'CARD_REMOVE_FAVOURITE_SUCCESS';
export const CARD_REMOVE_FAVOURITE_FAIL = 'CARD_REMOVE_FAVOURITE_FAIL';
export const CARD_REMOVE_GUEST_FAVOURITE_REQUESTED = 'CARD_REMOVE_GUEST_FAVOURITE_REQUESTED';
export const CARD_REMOVE_GUEST_FAVOURITE_SUCCESS = 'CARD_REMOVE_GUEST_FAVOURITE_SUCCESS';
export const CARD_REMOVE_GUEST_FAVOURITE_FAIL = 'CARD_REMOVE_GUEST_FAVOURITE_FAIL';
export const CARD_REMOVE_ALL_FAVOURITES = 'CARD_REMOVE_ALL_FAVOURITES';
export const CARD_EDIT_FAVOURITES = 'CARD_EDIT_FAVOURITES';




