export const PLANALL_REQUESTED = 'PLANALL_REQUESTED';
export const PLANALL_SUCCESS = 'PLANALL_SUCCESS';
export const PLANALL_FAIL = 'PLANALL_FAIL';
export const PLANALLDETAILS_REQUESTED = 'PLANALLDETAILS_REQUESTED';
export const PLANALLDETAILS_SUCCESS = 'PLANALLDETAILS_SUCCESS';
export const PLANALLDETAILS_FAIL = 'PLANALLDETAILS_FAIL';
export const PLANFAVOURITE_REQUESTED = 'PLANFAVOURITE_REQUESTED';
export const PLANFAVOURITE_SUCCESS = 'PLANFAVOURITE_SUCCESS';
export const PLANFAVOURITE_FAIL = 'PLANFAVOURITE_FAIL';
export const PLANFAVOURITELIST_REQUESTED = 'PLANFAVOURITELIST_REQUESTED';
export const PLANFAVOURITELIST_SUCCESS = 'PLANFAVOURITELIST_SUCCESS';
export const PLANFAVOURITELIST_FAIL = 'PLANFAVOURITELIST_FAIL';
export const PLAN_GUEST_FAVOURITE_REQUESTED = 'PLAN_GUEST_FAVOURITE_REQUESTED';
export const PLAN_GUEST_FAVOURITE_SUCCESS = 'PLAN_GUEST_FAVOURITE_SUCCESS';
export const PLAN_GUEST_FAVOURITE_FAIL = 'PLAN_GUEST_FAVOURITE_FAIL';
export const PLAN_REMOVE_FAVOURITE_REQUESTED = 'PLAN_REMOVE_FAVOURITE_REQUESTED';
export const PLAN_REMOVE_FAVOURITE_SUCCESS = 'PLAN_REMOVE_FAVOURITE_SUCCESS';
export const PLAN_REMOVE_FAVOURITE_FAIL = 'PLAN_REMOVE_FAVOURITE_FAIL';
export const PLAN_REMOVE_GUEST_FAVOURITE_REQUESTED = 'PLAN_REMOVE_GUEST_FAVOURITE_REQUESTED';
export const PLAN_REMOVE_GUEST_FAVOURITE_SUCCESS = 'PLAN_REMOVE_GUEST_FAVOURITE_SUCCESS';
export const PLAN_REMOVE_GUEST_FAVOURITE_FAIL = 'PLAN_REMOVE_GUEST_FAVOURITE_FAIL';
export const PLAN_REMOVE_ALL_FAVOURITES = 'PLAN_REMOVE_ALL_FAVOURITES';



