export { default as CheckBox } from "./CheckBox";
export { default as TextInput } from "./TextInput";
export { default as Title } from "./Title";
export { default as EmptyRecord } from "./EmptyRecord";
export { default as Tab } from "./Tab";
export { default as StickButton } from "./StickButton";
export { default as RadioButton } from "./RadioButton";
export { default as Switch } from "./Switch";
export { default as Button } from "./Button";
// export {default as Accordion} from './Accordion';
export { default as Rating } from "./Rating";
export { default as Statusbar } from "./Statusbar";
export { default as OtpInput } from "./OtpInput";
export { default as TextInputSimple } from "./TextInputSimple";
// export {default as CountryPicker} from './CoutryPicker';
