export const REVIEWALL_REQUESTED = 'REVIEWALL_REQUESTED';
export const REVIEWALL_SUCCESS = 'REVIEWALL_SUCCESS';
export const REVIEWALL_FAIL = 'REVIEWALL_FAIL';
export const REVIEWALLDETAILS_REQUESTED = 'REVIEWALLDETAILS_REQUESTED';
export const REVIEWALLDETAILS_SUCCESS = 'REVIEWALLDETAILS_SUCCESS';
export const REVIEWALLDETAILS_FAIL = 'REVIEWALLDETAILS_FAIL';
export const REVIEWFAVOURITE_REQUESTED = 'REVIEWFAVOURITE_REQUESTED';
export const REVIEWFAVOURITE_SUCCESS = 'REVIEWFAVOURITE_SUCCESS';
export const REVIEWFAVOURITE_FAIL = 'REVIEWFAVOURITE_FAIL';
export const REVIEWFAVOURITELIST_REQUESTED = 'REVIEWFAVOURITELIST_REQUESTED';
export const REVIEWFAVOURITELIST_SUCCESS = 'REVIEWFAVOURITELIST_SUCCESS';
export const REVIEWFAVOURITELIST_FAIL = 'REVIEWFAVOURITELIST_FAIL';
export const REVIEW_GUEST_FAVOURITE_REQUESTED = 'REVIEW_GUEST_FAVOURITE_REQUESTED';
export const REVIEW_GUEST_FAVOURITE_SUCCESS = 'REVIEW_GUEST_FAVOURITE_SUCCESS';
export const REVIEW_GUEST_FAVOURITE_FAIL = 'REVIEW_GUEST_FAVOURITE_FAIL';
export const REVIEW_REMOVE_FAVOURITE_REQUESTED = 'REVIEW_REMOVE_FAVOURITE_REQUESTED';
export const REVIEW_REMOVE_FAVOURITE_SUCCESS = 'REVIEW_REMOVE_FAVOURITE_SUCCESS';
export const REVIEW_REMOVE_FAVOURITE_FAIL = 'REVIEW_REMOVE_FAVOURITE_FAIL';
export const REVIEW_REMOVE_GUEST_FAVOURITE_REQUESTED = 'REVIEW_REMOVE_GUEST_FAVOURITE_REQUESTED';
export const REVIEW_REMOVE_GUEST_FAVOURITE_SUCCESS = 'REVIEW_REMOVE_GUEST_FAVOURITE_SUCCESS';
export const REVIEW_REMOVE_GUEST_FAVOURITE_FAIL = 'REVIEW_REMOVE_GUEST_FAVOURITE_FAIL';
export const REVIEW_REMOVE_ALL_FAVOURITES = 'REVIEW_REMOVE_ALL_FAVOURITES';



